apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.service.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.service.name }}
  minReplicas: {{ .Values.app.pod.min }}
  maxReplicas: {{ .Values.app.pod.max }}
  targetCPUUtilizationPercentage: 50