apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.app.stack_name }}-scaledobject
  namespace: {{ .Values.app.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.app.stack_name }}
  minReplicaCount: {{ .Values.app.pod.min }}
  maxReplicaCount: {{ .Values.app.pod.max }}
  {{- if .Values.app.autoscaling.triggers }}
  triggers:
    {{- toYaml .Values.app.autoscaling.triggers | nindent 4 }}
  {{- end }}